export const CREATE_ACCOUNT_FIELDS = [
  {
    id: 1,
    name: "email",
    type: "email",
    placeholder: "Email Address",
    label: "Email Address",
    errorMessage: "It should be a valid email address",
    pattern: `^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z0-9.-]$`,
    required: true,
    half: true,
  },
  {
    id: 2,
    name: "phone",
    type: "number",
    placeholder: "Phone",
    errorMessage: "Phone no. should be of 10 digits",
    pattern: "^[0-9]{10}",
    label: "Phone",
    half: true,
  },
  {
    id: 3,
    name: "password",
    type: "password",
    placeholder: "Password",
    label: "Password",
    errorMessage:
      "password should be of 8-20 character and include at least 1 letter, 1 number and 1 special character",
    pattern: `^(?=.*?[A-Za-z])(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$`,
    required: true,
    half: true,
  },
  {
    id: 4,
    name: "confirmPassword",
    type: "password",
    placeholder: "Confirm Password",
    label: "Confirm Password",
    errorMessage: "Password doesn't match",
    pattern: ``,
    required: true,
    half: true,
  },
  {
    id: 5,
    name: "firtName",
    type: "text",
    placeholder: "First Name",
    label: "First Name",
    required: true,
    half: true,
  },
  {
    id: 6,
    name: "lastName",
    type: "text",
    placeholder: "Last Name",
    label: "Last Name",
    half: true,
  },
  {
    id: 7,
    name: "companyName",
    type: "text",
    placeholder: "Company Name",
    label: "Company Name",
  },
  {
    id: 8,
    name: "country",
    type: "text",
    placeholder: "Country",
    label: "Country",
    required: true,
  },
  {
    id: 9,
    name: "streetAddress",
    type: "text",
    placeholder: "Street Address",
    label: "Street Address",
    required: true,
  },
  {
    id: 10,
    name: "postalCode",
    type: "number",
    placeholder: "Postalcode / ZIP ",
    errorMessage: "Postalcode should be of 6 digit",
    label: "Postalcode / ZIP",
  },
  {
    id: 11,
    name: "state",
    type: "text",
    placeholder: "State",
    label: "State",
  },
  {
    id: 12,
    name: "town",
    type: "text",
    placeholder: "Town / City",
    label: "Town / City",
  },
];
