export const productTypes = {
    PRODUCTS_FETCH: 'PRODUCTS_FETCH',
    PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
    PRODUCTS_ERROR: 'PRODUCTS_ERROR',
    PRODUCTS_RESET: 'PRODUCTS_RESET'
};
export const categoryTypes = {
    CATEGORIES_FETCH: 'CATEGORIES_FETCH',
    CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
    CATEGORIES_ERROR: 'CATEGORIES_ERROR',
    CATEGORIES_RESET: 'CATEGORIES_RESET'
};